stages:
  - pytest
  - build
  - test

variables:
  GIT_STRATEGY: clone
  VERSION_NUMBER: "1.0.0"
  CONTAINER_NAME: "newmath"

before_script:
  - set -x # Debug/interpretation mode.
  - whoami # Who's running the CI?
  - env    # spits out all environment variables (including CI)
  - ls     # shows the current directory contents for debugging.



run_pytest:
  stage: pytest
  script:
    - python3 -m pytest -v --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml


build:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/${CONTAINER_NAME}:${VERSION_NUMBER}
  script:
    - whoami
    - echo $PATH
    - podman build -t $IMAGE_TAG . 
    - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - /usr/bin/podman push $IMAGE_TAG
  only:
    - master

